CONFIG_PARAM_TURN_TIME = "TURN_TIME"
CONFIG_PARAM_LOG_LEVEL = "LOG_LEVEL"
CONFIG_PARAM_QUEUE_HOST = "QUEUE_HOST"
CONFIG_PARAM_QUEUE_PORT = "QUEUE_PORT"
CONFIG_PARAM_NEW_PATH = "CONFIG_PATH"
CONFIG_PARAM_CONFIG_RELOAD_TIME = "CONFIG_RELOAD_TIME"
CONFIG_PARAM_BOT_SECRET = "BOT_SECRET"

CMD_CREATE_CHARACTER = "create_character"
CMD_DELETE_CHARACTER = "delete_character"
CMD_GET_CHARACTER_STATUS = "get_character_status"

QUEUE_NAME_INIT = "InitQueue"
QUEUE_NAME_DICT = "DictionaryQueue"
QUEUE_NAME_CMD = "CommandQueue"
QUEUE_NAME_RESPONSES = "ResponsesQueue"

MAIN_MENU_CREATE = "main_create"
MAIN_MENU_STATUS = "main_status"
MAIN_MENU_DELETE = "main_delete"

STAGE_SELECT_CLASS = "select_class"
STAGE_CHOOSE_NAME = "choose name"
STAGE_CONFIRM_DELETION = "CONFIRM_DELETION"

LOG_CONFIG = "Config"
LOG_MAIN = "Main"
LOG_QUEUE = "Queue"
LOG_TELEGRAM = "Telegram"
